# This configuration file is for **development** setup. For production, refer to
# docker-compose.production.yml.
version: '2'
services:
  server:
    image: &docker-image redash/redash:4.0.0-rc.1
    command: dev_server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_HOST: "http://localhost:5000/"
      REDASH_MAIL_SERVER: "smtp.mailtrap.io"
      REDASH_MAIL_PORT: 2525
      REDASH_MAIL_USE_TLS: "False"
      REDASH_MAIL_USERNAME: "899d4e97324fb4"
      REDASH_MAIL_PASSWORD: "6e347363386ce8"
      REDASH_MAIL_DEFAULT_SENDER: "e93d637d9b-e22cc7@inbox.mailtrap.io"
  worker:
    image: *docker-image
    command: scheduler
    volumes_from:
      - server
    depends_on:
      - server
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
  redis:
    image: redis:4.0-alpine
    restart: unless-stopped
    volumes:
      - ./redis:/data
  postgres:
    image: postgres:9.5.6-alpine
    # The following turns the DB into less durable, but gains significant performance improvements for the tests run (x3
    # improvement on my personal machine). We should consider moving this into a dedicated Docker Compose configuration for
    # tests.
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
  mysql:
    image: kakakakakku/mysql-57-world-database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

